[package]
name = "sp-maybe-compressed-blob"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Handling of blobs, usually Wasm code, which may be compresed"
documentation = "https://docs.rs/sp-maybe-compressed-blob"
readme = "README.md"

[dependencies]
impl-trait-for-tuples = "0.2.1"
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
zstd = { version = "0.6.0", optional = true }
ruzstd = { version = "0.2.2", optional = true }

[features]
default = []
zstd_c = ["zstd"]
zstd_rust = []
encode = ["zstd"]
